In [1]:
import numpy as np

# Exercise 1: Create a 1D Array
### Problem: Create a NumPy array containing the numbers from 1 to 20 (inclusive).
### Expected Output:
#### [ 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20]

In [2]:
arr = np.arange(1, 21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


# Exercise 2: Create a Matrix of Zeros
### Problem: Create a 5×5 matrix (2D array) filled with zeros.
### Expected Output:
#### [[0. 0. 0. 0. 0.]
#### [0. 0. 0. 0. 0.]
#### [0. 0. 0. 0. 0.]
#### [0. 0. 0. 0. 0.]
#### [0. 0. 0. 0. 0.]]

In [3]:
zeros = np.zeros((5, 5))
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


## Exercise 3: Extract Elements

In [4]:
arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120]])

# 1. Element at [2,3]
print(arr[2, 3])

# 2. 3rd row
print(arr[2])

# 3. 2nd column
print(arr[:, 1])

120
[ 90 100 110 120]
[ 20  60 100]


## Exercise 4: Boolean Filtering

In [5]:
scores = np.array([75, 82, 90, 68, 85, 92, 78, 88, 95, 72])

result = scores[scores >= 80]
print(result)

[82 90 85 92 88 95]


## Exercise 5: Statistics

In [6]:
temps = np.array([72, 75, 78, 82, 79, 73, 76, 80, 77, 74])

print("Mean:", np.mean(temps))
print("Max:", np.max(temps))
print("Min:", np.min(temps))
print("Std Dev:", np.std(temps))

Mean: 76.6
Max: 82
Min: 72
Std Dev: 3.0397368307141326


## Exercise 6: Reshape Array

In [7]:
arr = np.arange(1, 13).reshape(3, 4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## Exercise 7: Element-wise Operations

In [8]:
a = np.array([10, 20, 30, 40, 50])
b = np.array([5, 25, 15, 35, 45])

print(a + b)        # Add
print(a * b)        # Multiply
print(a > b)        # Comparison

[15 45 45 75 95]
[  50  500  450 1400 2250]
[ True False  True  True  True]


## Exercise 8: Random Array

In [9]:
rand_arr = np.random.randint(1, 101, (4, 5))

print(rand_arr)
print("Shape:", rand_arr.shape)

[[63 41 68 87 36]
 [56 29 84 72 18]
 [76 30 66 15 53]
 [42 21 10 58 75]]
Shape: (4, 5)


## Exercise 9: Sub-array (Center 2×2)

In [10]:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

sub = matrix[1:3, 1:3]
print(sub)

[[ 6  7]
 [10 11]]


## Exercise 10: Broadcasting

In [11]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

to_add = np.array([100, 200, 300])

result = matrix + to_add
print(result)

[[101 202 303]
 [104 205 306]
 [107 208 309]]
