# Machine Learning Foundations – Lecture 1
## NumPy for Data Analysis and Machine Learning

**Course Context:** NAVTTC AI / Machine Learning Program  
**Instructor:** Ayesha  

---

## Learning Objectives
By the end of this lecture students will be able to:

- Understand why **NumPy is important for Machine Learning**
- Create NumPy arrays from lists, built‑in methods and random data
- Explore **array attributes** used in ML pipelines
- Perform **array operations used in real ML preprocessing**
- Apply **indexing and logical selection** on real‑world data
- Understand **broadcasting and vectorized operations**
- Use **universal functions** for fast numerical computation

---

## Why NumPy is Important in Machine Learning

Machine Learning algorithms work with **numerical data stored in vectors and matrices**.

Examples:

- A dataset → matrix
- A feature column → vector
- Neural network weights → matrices

NumPy provides:

- Fast numerical computation
- Efficient matrix operations
- Vectorized calculations

Almost every ML library depends on NumPy:

- Pandas
- Scikit‑Learn
- TensorFlow
- PyTorch


---
## 📖 How to Use This Notebook

Welcome to interactive NumPy learning! This notebook will help you master NumPy through hands-on practice.

### What's Inside:
- 📚 **Clear Explanations** - Understand concepts step-by-step
- 💻 **Live Examples** - See code in action
- 🎯 **Practice Exercises** - Test your skills
- 💡 **Hints** - Get help when stuck (click to reveal)
- ✅ **Solutions** - Check your work (attempt first!)

### How to Learn:
1. **Read** each concept carefully
2. **Run** code cells (press ▶️ or Shift+Enter)
3. **Try** exercises yourself before checking hints
4. **Experiment** - change values and see what happens!
5. **Practice** - repetition builds mastery

### 💡 Pro Tips:
- Don't just read - **type** the code yourself
- Make mistakes! They're the best teachers
- Ask "What if...?" and test your ideas
- Connect concepts to real ML applications

**Ready? Let's dive in!** 🚀
---


# Why Do We Need NumPy?

Before NumPy, Python used lists to store data.

Problems with lists:
- Slow for large data
- Cannot perform mathematical operations easily
- Not efficient for numerical computations

Example: 
If we want to multiply all values by 2, we need loops.

NumPy solves this problem.

### Key Differences

| Feature | Python List | NumPy Array |
|---|---|---|
| Speed | Slow | Very Fast |
| Data Type | Mixed allowed | Same type |
| Math Operations | Not optimized | Vectorized |
| Used in ML | Rarely | Always |

Example:


In [119]:
# Without Numpy
data = [1,2,3,4,5]

result = []
for i in data:
    result.append(i*2)

print(result)

[2, 4, 6, 8, 10]


In [120]:
import numpy as np

In [121]:
arr = np.array(a)
arr*2


array([ 4,  6,  8, 10, 12])

In [122]:
a = [2,3,4,5]
print(type(a))

arr = np.array(a)
print(type(arr))


<class 'list'>
<class 'numpy.ndarray'>


In [123]:
b =[2,3,'a', 3.5,True]
arr2 = np.array(b)
print(arr2)
arr2.dtype

['2' '3' 'a' '3.5' 'True']


dtype('<U32')

In [124]:
import time

num_list = list(range(10000000))
num_array = np.array(num_list)


In [125]:
# With python

start = time.time()
mean1 = sum(num_list)/len(num_list)
end = time.time()

print('python mean: ',mean1)
print('Time taken:', end-start)


python mean:  4999999.5
Time taken: 0.07637286186218262


In [126]:
start = time.time()
mean2 = np.mean(num_array)
end= time.time()

print('Numpy mean:',mean2)
print('Time taken:', end-start)

Numpy mean: 4999999.5
Time taken: 0.018553495407104492


**Numpy is Faster** because python calculates mean using loops internally. Numpy uses optimized C code and Vectorized operations, so it avoids loops and run faster.

A **vectorized operation** in NumPy means applying an operation to an entire array at once, rather than looping over elements one by one.

**Basic Array creation**

we can create arrays in multiple ways:

1. From python list
2. Using built-in Numpy functions
3. Using random values

In [127]:
# Arrays from List and tuple.

a = [2,3,4,5,6]
b =(6,7,8,9)
arr = np.array(a)
arr1 = np.array(b)
print(arr)
print(arr1)

[2 3 4 5 6]
[6 7 8 9]


In [128]:
a = [[1,2,3,4],[3,4,5,6]]                #: Imagine a dataset of 1000 patients with 5 health measurements each.This becomes a 2D NumPy array of shape (1000, 5). 
arr = np.array(a)
arr

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [129]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [130]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Array generation (BUILT-IN METHODS)**

In [131]:
# CREATES NUMBERS IN SEQUENCE....used for indexing and plotting.

arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [134]:
# It is used in AI to initialize variables ,weights or empty data structures before filling them with real ones.

arr = np.zeros(8)
arr

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [135]:
arr = np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [136]:
# It is used in AI to initialize data, weights or matrices when a uniform starting value is needed.

arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
# Used in AI for: learning rate schedules (gradually reducing learning rate), plotting smooth curves in graphs, creating probability distributions, and normalizing data to 0-1 range.

In [137]:
# create numbers evenly spaced between a start and end value. Used in scalling

arr = np.linspace(0,1,10)
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

**Random Generation function**

In [142]:
# Generate random decimal number between 0 and 1. Used for data shuffling.
np.random.rand(10)

array([0.08154195, 0.01335899, 0.46796682, 0.0292945 , 0.51234611,
       0.08142546, 0.84404122, 0.34240873, 0.78045355, 0.20029049])

In [145]:
# Values can be negative and positive, centered around 0.

np.random.randn(10)

array([-0.98758079, -1.59055854,  0.53932313, -0.32053166,  1.824762  ,
       -0.35664014,  0.23118778, -1.19697481, -1.87778744,  0.3502299 ])

In [148]:
# generates random integers within a given range.

np.random.randint(10,20,10)

array([11, 16, 14, 17, 17, 17, 19, 10, 11, 14], dtype=int32)

**Array Attributes**

In [149]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [150]:
# Returns number of dimensions (1D, 2D, etc.)
arr.ndim

2

In [151]:
# Returns the dimensions of the array (rows, columns).
arr.shape

(3, 3)

In [152]:
# Gives total number of elements in the array.
arr.size

9

In [153]:
# Shows the data type of array elements (e.g., int, float).
arr.dtype

dtype('int64')

---
## 🎯 Practice Exercise 1: Creating NumPy Arrays

**Time to practice!** Let's solidify your array creation skills.

### 📝 Your Tasks:
Complete these array creation challenges:

1. Create a 1D array with numbers from **0 to 15**
2. Create a **4×3** matrix filled with zeros
3. Create a **2×5** matrix filled with ones  
5. Create an array of **12 evenly spaced** values between 0 and 100
6. Create a **3×4** array with random integers between **10 and 50**

<details>
<summary>💡 <b>Click here for Hints</b></summary>

**Functions you'll need:**
- `np.arange(start, stop)` - Creates sequence of numbers
- `np.zeros((rows, cols))` - Creates array of zeros
- `np.ones((rows, cols))` - Creates array of ones  
- `np.eye(n)` - Creates n×n identity matrix
- `np.linspace(start, stop, count)` - Creates evenly spaced values
- `np.random.randint(low, high, (rows, cols))` - Random integers
- `np.full((shape), value)` - Creates array filled with specific value

**Remember:** 
- Shape goes in parentheses: `(rows, cols)` or `(dim1, dim2, dim3)`
- `arange(15)` gives 0-14, `arange(16)` gives 0-15

</details>


In [ ]:
# 🎯 Exercise 1: Array Creation Practice
import numpy as np

# Task 1: Array from 0 to 15
arr1 = # Your code here
print('Task 1:', arr1)

# Task 2: 4×3 matrix of zeros
arr2 = # Your code here
print('Task 2:\n', arr2)

# Task 3: 2×5 matrix of ones
arr3 = # Your code here
print('Task 3:\n', arr3)

# Task 4: 3×3 identity matrix
arr4 = # Your code here
print('Task 4:\n', arr4)

# Task 5: 12 evenly spaced values between 0 and 100
arr5 = # Your code here
print('Task 5:', arr5)

# Task 6: 3×4 array with random integers 10-50
arr6 = # Your code here
print('Task 6:\n', arr6)

# Task 7: 2×2×3 array filled with 5
arr7 = # Your code here
print('Task 7:\n', arr7)


<details>
<summary>✅ <b>Click here for Solutions</b></summary>

```python
import numpy as np

# Task 1: Array from 0 to 15
arr1 = np.arange(16)  # 0 to 15 (16 not included)
print('Task 1:', arr1)
# Output: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

# Task 2: 4×3 matrix of zeros
arr2 = np.zeros((4, 3))
print('Task 2:\n', arr2)
# Output: 4 rows, 3 columns of 0.0

# Task 3: 2×5 matrix of ones
arr3 = np.ones((2, 5))
print('Task 3:\n', arr3)
# Output: 2 rows, 5 columns of 1.0

# Task 4: 3×3 identity matrix
arr4 = np.eye(3)
print('Task 4:\n', arr4)
# Output:
# [[1. 0. 0.]
#  [0. 1. 0.]
#  [0. 0. 1.]]

# Task 5: 12 evenly spaced values between 0 and 100
arr5 = np.linspace(0, 100, 12)
print('Task 5:', arr5)
# Output: [  0.   9.09  18.18 ... 90.91 100. ]

# Task 6: 3×4 array with random integers 10-50
arr6 = np.random.randint(10, 51, (3, 4))  # 51 because upper bound is exclusive
print('Task 6:\n', arr6)
# Output: Random values like [[23 45 12 38] [19 50 27 41] [15 33 48 22]]

# Task 7: 2×2×3 array filled with 5
arr7 = np.full((2, 2, 3), 5)
print('Task 7:\n', arr7)
# Output: 3D array with all values = 5
```

**🎉 Great job!** You've mastered array creation!

**Key Takeaways:**
- Use `arange()` for sequences, `linspace()` for evenly spaced values
- Always use **tuple** for shape: `(rows, cols)`
- Random upper bound is **exclusive**: use 51 to include 50
- Identity matrix diagonal = 1, everything else = 0

</details>
---


**TYPECASTING**

In [155]:
arr = np.array([1,2,3,4])
arr.dtype

dtype('int64')

In [156]:
import numpy as np

arr = np.array([1, 2, 3])
print(arr.dtype)

# convert to float
new_arr = arr.astype(float)

print(new_arr)
new_arr.dtype

int64
[1. 2. 3.]


dtype('float64')

**Array Methods**

In [157]:
arr = np.array([[3,4,5,6],[6,7,8,9]])
arr

array([[3, 4, 5, 6],
       [6, 7, 8, 9]])

In [158]:
# Returns the manimum value in the array.
print(arr.min())

3


In [159]:
# Returns the maximum value in the array.
m =arr.max()
print(m)


9


In [160]:
# Returns the total sum of all elements in the array.

arr.sum()

np.int64(48)

In [ ]:
np.sum(arr)

np.int64(48)

In [164]:
# Calculates the average (mean) value of the array elements.
arr.mean()

np.float64(6.0)

In [165]:
# Measures how much the values in the array vary from the mean.

arr.std()

np.float64(1.8708286933869707)

In [166]:
np.std(arr)

np.float64(1.8708286933869707)

In [167]:
# Returns the index of the miximum value.

arr.argmax()

np.int64(7)

In [168]:
# Returns the index of the minimum value.
arr.argmin()

np.int64(0)

**Reshaping and resizing**

### Reshaping means changing the shape of an array without changing its data. This is one of the most used operations in AI because data often comes in one shape and your model needs it in another shape.

In [169]:

arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [171]:
# Changes the shape of the array without changing its data.
arr2 = arr.reshape(5,6)
print(arr2)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]


In [172]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
# NumPy resize changes the shape and size of an array by adding or removing elements.
# It modifies the original array and fills extra spaces with zeros if needed.

In [174]:
arr2= np.resize(arr,(7,8))
print(arr2)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30  1  2]
 [ 3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26]]


In [175]:
arr1 = np.array([4,5,6,7])
arr2=np.resize(arr1,(2,6))
arr2

array([[4, 5, 6, 7, 4, 5],
       [6, 7, 4, 5, 6, 7]])

- **Slicing** → Used in AI to extract parts of data like images, features, batches, and training/testing sets. 
- **Indexing** → Used to access specific values or outputs for filtering, predictions, and data selection.

**NUMPY INDEXING AND SLICING OF VECTORS**

In [176]:
arr = np.arange(11,30)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29])

In [177]:
arr[7]

np.int64(18)

In [178]:
arr[2:7]

array([13, 14, 15, 16, 17])

In [179]:
arr[:8]

array([11, 12, 13, 14, 15, 16, 17, 18])

In [180]:
arr[4::3]

array([15, 18, 21, 24, 27])

**NUMPY INDEXCING AND SLICING OF MATRIX**

In [181]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [182]:
arr[0]

array([1, 2, 3, 4, 5])

In [183]:
arr[5]

array([26, 27, 28, 29, 30])

In [184]:
arr[2:5]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [185]:
arr[1,4]

np.int64(10)

In [186]:
arr[2:5,3:5]

array([[14, 15],
       [19, 20],
       [24, 25]])

In [187]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

---
## 🎯 Practice Exercise 2: Indexing & Slicing Mastery

**Time to become a slicing ninja!** 🥷

### 📊 Given this data array:
```python
data = np.array([[100, 200, 300, 400, 500],
                 [600, 700, 800, 900, 1000],
                 [1100, 1200, 1300, 1400, 1500],
                 [1600, 1700, 1800, 1900, 2000]])
```

### 📝 Your Tasks:
Extract the following using indexing and slicing:

1. The element **800** (row 1, column 2)
2. The **entire first row** [100, 200, 300, 400, 500]
3. The **entire last column** [500, 1000, 1500, 2000]
4. The **first 2 rows and first 3 columns** (2×3 sub-array)
5. The **middle 2×2 block** [[700, 800], [1200, 1300]]
6. **Every other element** from the second row
7. All elements in the **third column**
8. Get the **bottom-right 2×2** corner

<details>
<summary>💡 <b>Click here for Hints</b></summary>

**Indexing Cheat Sheet:**
- Single element: `arr[row, col]` (remember: 0-based indexing!)
- Entire row: `arr[row, :]` or just `arr[row]`
- Entire column: `arr[:, col]`
- Slicing range: `arr[start:end, start:end]` (end is exclusive)
- Boolean indexing: `arr[arr > value]`
- Negative indexing: `-1` = last, `-2` = second to last
- Step slicing: `arr[::2]` = every other element

**Common Patterns:**
- First 2 rows: `arr[:2, :]`
- Last column: `arr[:, -1]`
- Replace values: `arr[arr > 1500] = 9999`

</details>


In [ ]:
# 🎯 Exercise 2: Indexing & Slicing Practice
import numpy as np

data = np.array([[100, 200, 300, 400, 500],
                 [600, 700, 800, 900, 1000],
                 [1100, 1200, 1300, 1400, 1500],
                 [1600, 1700, 1800, 1900, 2000]])

print('Original Data:\n', data)
print('Shape:', data.shape)
print('\n' + '='*50 + '\n')

# Task 1: Get element 800
element = # Your code here
print('Task 1 (800):', element)

# Task 2: Entire first row
first_row = # Your code here
print('Task 2 (first row):', first_row)

# Task 3: Entire last column
last_col = # Your code here
print('Task 3 (last column):', last_col)

# Task 4: First 2 rows, first 3 columns
subarray = # Your code here
print('Task 4 (2x3 sub-array):\n', subarray)

# Task 5: All elements > 1000
filtered = # Your code here
print('Task 5 (elements > 1000):', filtered)

# Task 6: Middle 2×2 block
middle = # Your code here
print('Task 6 (middle 2x2):\n', middle)

# Task 7: Every other element from second row
every_other = # Your code here
print('Task 7 (every other from row 2):', every_other)

# Task 8: All elements in third column
third_col = # Your code here
print('Task 8 (third column):', third_col)

# Task 9: Replace values > 1500 with 9999
data_copy = data.copy()  # Make a copy to preserve original
# Your code here
print('Task 9 (replaced > 1500):\n', data_copy)

# Task 10: Bottom-right 2×2 corner
corner = # Your code here
print('Task 10 (bottom-right 2x2):\n', corner)


<details>
<summary>✅ <b>Click here for Solutions</b></summary>

```python
import numpy as np

data = np.array([[100, 200, 300, 400, 500],
                 [600, 700, 800, 900, 1000],
                 [1100, 1200, 1300, 1400, 1500],
                 [1600, 1700, 1800, 1900, 2000]])

# Task 1: Get element 800 (row 1, col 2 - remember 0-indexing!)
element = data[1, 2]
print('Task 1:', element)  # 800

# Task 2: Entire first row (index 0)
first_row = data[0, :]
# or simply: data[0]
print('Task 2:', first_row)  # [100 200 300 400 500]

# Task 3: Entire last column (index -1 or 4)
last_col = data[:, -1]
# or: data[:, 4]
print('Task 3:', last_col)  # [ 500 1000 1500 2000]

# Task 4: First 2 rows, first 3 columns
subarray = data[:2, :3]
print('Task 4:\n', subarray)
# [[100 200 300]
#  [600 700 800]]

# Task 5: All elements > 1000
filtered = data[data > 1000]
print('Task 5:', filtered)
# [1100 1200 1300 1400 1500 1600 1700 1800 1900 2000]

# Task 6: Middle 2×2 block (rows 1-2, cols 1-2)
middle = data[1:3, 1:3]
print('Task 6:\n', middle)
# [[ 700  800]
#  [1200 1300]]

# Task 7: Every other element from second row (index 1)
every_other = data[1, ::2]
print('Task 7:', every_other)  # [600 800 1000]

# Task 8: All elements in third column (index 2)
third_col = data[:, 2]
print('Task 8:', third_col)  # [ 300  800 1300 1800]

# Task 9: Replace values > 1500 with 9999
data_copy = data.copy()
data_copy[data_copy > 1500] = 9999
print('Task 9:\n', data_copy)
# [[ 100  200  300  400  500]
#  [ 600  700  800  900 1000]
#  [1100 1200 1300 1400 1500]
#  [9999 9999 9999 9999 9999]]

# Task 10: Bottom-right 2×2 corner
corner = data[-2:, -2:]
# or: data[2:4, 3:5]
print('Task 10:\n', corner)
# [[1400 1500]
#  [1900 2000]]
```

**🎉 Excellent work!** You're now a slicing expert!

**Key Insights:**
- **Negative indexing** is powerful: `-1` = last, `-2` = second to last
- **Boolean indexing** returns a 1D array of matching elements
- **Slicing** preserves dimensions: `arr[1:3, 1:3]` gives 2D result
- **Step slicing** `[::2]` means "every other element"
- Always use `.copy()` when modifying to preserve original!

</details>
---


****ARRAY OPERATIONS****

*Arithmetic operations*

In [188]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [189]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [190]:
a1 -a2 

array([-5, -5, -5, -5, -5])

In [191]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [192]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [193]:
a1 // a2

array([0, 0, 0, 0, 0])

In [194]:
a1 ** a2 

array([      1,     128,    6561,  262144, 9765625])

---
## 🎯 Practice Exercise 3: Array Operations & Statistics

**Let's master NumPy operations!** 🧮

### 📝 Your Tasks:

**Part A: Basic Operations**
1. Create two arrays: `a = [10, 20, 30, 40, 50]` and `b = [5, 10, 15, 20, 25]`
2. Add them **element-wise**
3. Subtract `b` from `a`
4. Multiply `a` by **3** (scalar multiplication)
5. Divide `a` by `b` element-wise
6. Find `a` **raised to power 2** (square each element)
7. Calculate the **dot product** of `a` and `b`

**Part B: Mathematical Functions**
8. Find **square root** of all elements in `a`
9. Calculate **exponential** (e^x) for array `[1, 2, 3]`
10. Find **sine** of array `[0, π/2, π]` (use `np.pi`)

**Part C: Statistics**
Given this test scores array:
```python
scores = np.array([85, 92, 78, 90, 88, 76, 95, 82, 89, 91])
```
11. Calculate the **mean** (average)
12. Find the **median** (middle value)
13. Calculate **standard deviation**
14. Find **minimum** and **maximum** scores
15. Calculate the **sum** of all scores
16. Count how many scores are **above 85**

<details>
<summary>💡 <b>Click here for Hints</b></summary>

**Arithmetic Operations:**
- Element-wise: `a + b`, `a - b`, `a * b`, `a / b`
- Scalar: `a * 3`, `a + 10`
- Power: `a ** 2` or `np.power(a, 2)`
- Dot product: `np.dot(a, b)`

**Math Functions:**
- `np.sqrt(arr)` - Square root
- `np.exp(arr)` - Exponential
- `np.sin(arr)`, `np.cos(arr)` - Trigonometric
- `np.pi` - Value of π

**Statistics:**
- `np.mean(arr)` - Average
- `np.median(arr)` - Middle value
- `np.std(arr)` - Standard deviation
- `np.min(arr)`, `np.max(arr)` - Min/Max
- `np.sum(arr)` - Total
- `np.sum(arr > 85)` - Count matching elements

</details>


In [ ]:
# 🎯 Exercise 3: Operations & Statistics Practice
import numpy as np

print('='*60)
print('PART A: BASIC OPERATIONS')
print('='*60)

# Task 1: Create arrays
a = np.array([10, 20, 30, 40, 50])
b = np.array([5, 10, 15, 20, 25])
print('Array a:', a)
print('Array b:', b)
print()

# Task 2: Add element-wise
addition = # Your code here
print('Task 2 (a + b):', addition)

# Task 3: Subtract b from a
subtraction = # Your code here
print('Task 3 (a - b):', subtraction)

# Task 4: Multiply a by 3
multiply = # Your code here
print('Task 4 (a * 3):', multiply)

# Task 5: Divide a by b
division = # Your code here
print('Task 5 (a / b):', division)

# Task 6: Square each element of a
squared = # Your code here
print('Task 6 (a²):', squared)

# Task 7: Dot product
dot_product = # Your code here
print('Task 7 (dot product):', dot_product)

print('\n' + '='*60)
print('PART B: MATHEMATICAL FUNCTIONS')
print('='*60 + '\n')

# Task 8: Square root of a
sqrt_a = # Your code here
print('Task 8 (√a):', sqrt_a)

# Task 9: Exponential of [1, 2, 3]
exp_arr = # Your code here
print('Task 9 (e^x):', exp_arr)

# Task 10: Sine of [0, π/2, π]
sin_arr = # Your code here
print('Task 10 (sin):', sin_arr)

print('\n' + '='*60)
print('PART C: STATISTICS')
print('='*60 + '\n')

scores = np.array([85, 92, 78, 90, 88, 76, 95, 82, 89, 91])
print('Test Scores:', scores)
print()

# Task 11: Mean
mean_score = # Your code here
print('Task 11 (Mean):', mean_score)

# Task 12: Median
median_score = # Your code here
print('Task 12 (Median):', median_score)

# Task 13: Standard deviation
std_score = # Your code here
print('Task 13 (Std Dev):', std_score)

# Task 14: Min and Max
min_score = # Your code here
max_score = # Your code here
print('Task 14 (Min, Max):', min_score, max_score)

# Task 15: Sum
total = # Your code here
print('Task 15 (Total):', total)

# Task 16: Count scores > 85
count_above_85 = # Your code here
print('Task 16 (Count > 85):', count_above_85)


<details>
<summary>✅ <b>Click here for Solutions</b></summary>

```python
import numpy as np

# PART A: BASIC OPERATIONS
a = np.array([10, 20, 30, 40, 50])
b = np.array([5, 10, 15, 20, 25])

# Task 2: Add element-wise
addition = a + b
print('Task 2:', addition)  # [15 30 45 60 75]

# Task 3: Subtract
subtraction = a - b
print('Task 3:', subtraction)  # [5 10 15 20 25]

# Task 4: Multiply by scalar
multiply = a * 3
print('Task 4:', multiply)  # [ 30  60  90 120 150]

# Task 5: Divide
division = a / b
print('Task 5:', division)  # [2. 2. 2. 2. 2.]

# Task 6: Square
squared = a ** 2
# or: np.power(a, 2)
print('Task 6:', squared)  # [ 100  400  900 1600 2500]

# Task 7: Dot product
dot_product = np.dot(a, b)
print('Task 7:', dot_product)  # 2750
# Calculation: 10*5 + 20*10 + 30*15 + 40*20 + 50*25 = 2750

# PART B: MATHEMATICAL FUNCTIONS

# Task 8: Square root
sqrt_a = np.sqrt(a)
print('Task 8:', sqrt_a)  # [3.162  4.472  5.477  6.325  7.071]

# Task 9: Exponential
exp_arr = np.exp([1, 2, 3])
print('Task 9:', exp_arr)  # [ 2.718  7.389 20.086]

# Task 10: Sine
sin_arr = np.sin([0, np.pi/2, np.pi])
print('Task 10:', sin_arr)  # [0.  1.  0.] (approximately)

# PART C: STATISTICS

scores = np.array([85, 92, 78, 90, 88, 76, 95, 82, 89, 91])

# Task 11: Mean
mean_score = np.mean(scores)
print('Task 11 (Mean):', mean_score)  # 86.6

# Task 12: Median
median_score = np.median(scores)
print('Task 12 (Median):', median_score)  # 88.5

# Task 13: Standard deviation
std_score = np.std(scores)
print('Task 13 (Std Dev):', std_score)  # 5.73

# Task 14: Min and Max
min_score = np.min(scores)
max_score = np.max(scores)
print('Task 14:', min_score, max_score)  # 76, 95

# Task 15: Sum
total = np.sum(scores)
print('Task 15 (Total):', total)  # 866

# Task 16: Count > 85
count_above_85 = np.sum(scores > 85)
print('Task 16:', count_above_85)  # 7 students
```

**🎉 Fantastic!** You've mastered NumPy operations!

**Key Learnings:**
- **Vectorization**: Operations apply to entire arrays automatically
- **Element-wise vs Dot Product**: `a * b` ≠ `np.dot(a, b)`
- **Boolean tricks**: `np.sum(arr > 85)` counts True values (True=1, False=0)
- **Why it matters in ML**:
  - Mean/Std: Used for data normalization
  - Dot product: Core of neural network computations
  - Statistics: Understanding data distribution

</details>
---


## *Broadcasting*......used to match array sizes automatically

In [195]:
l = [10,20,30,40]
arr = np.array(l)

In [196]:
arr + 10 

array([20, 30, 40, 50])

In [197]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [198]:
arr2 = arr2 + 10
arr2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

---
## 🎯 Practice Exercise 4: Broadcasting Magic ✨

**Unlock the power of broadcasting!** This is one of NumPy's most powerful features.

### 📝 Your Tasks:

**Part A: Scalar Broadcasting**
1. Create a **3×4** array of ones and add **10** to all elements
2. Create array `[5, 10, 15, 20]` and multiply by **5**
3. Create a **2×3** array of random values and subtract **0.5** from all

**Part B: 1D to 2D Broadcasting**
4. Create this matrix and multiplier:
```python
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
multiplier = np.array([10, 20, 30])
```
Multiply each **column** by the multiplier

5. Add `[100, 200, 300]` to **each row** of the matrix above

**Part C: Real-World Application**
6. Normalize this student grades array (subtract mean, divide by std):
```python
grades = np.array([[85, 90, 78],
                   [92, 88, 76],
                   [79, 95, 82]])
```

7. Convert temperatures from Celsius to Fahrenheit:
```python
celsius = np.array([[0, 10, 20],
                    [30, 40, 50]])
# Formula: F = C × 9/5 + 32
```

<details>
<summary>💡 <b>Click here for Hints</b></summary>

**Broadcasting Rules:**
- Scalar + Array: Scalar broadcasts to all elements
- 1D + 2D: If shapes align, smaller array broadcasts
- Column-wise multiply: `matrix * multiplier` (if shapes match)
- Row-wise add: `matrix + row_array`

**Normalization:**
1. Calculate mean: `arr.mean()`
2. Calculate std: `arr.std()`
3. Normalize: `(arr - mean) / std`

**Temperature Conversion:**
- Apply formula to entire array: `celsius * 9/5 + 32`
- Broadcasting handles it automatically!

</details>


In [ ]:
# 🎯 Exercise 4: Broadcasting Practice
import numpy as np

print('='*60)
print('PART A: SCALAR BROADCASTING')
print('='*60 + '\n')

# Task 1: 3×4 ones + 10
arr1 = # Your code here
print('Task 1 (ones + 10):\n', arr1)
print()

# Task 2: [5,10,15,20] * 5
arr2 = # Your code here
print('Task 2 (array * 5):', arr2)
print()

# Task 3: Random 2×3 - 0.5
arr3 = # Your code here
print('Task 3 (random - 0.5):\n', arr3)

print('\n' + '='*60)
print('PART B: 1D to 2D BROADCASTING')
print('='*60 + '\n')

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
multiplier = np.array([10, 20, 30])

print('Original Matrix:\n', matrix)
print('Multiplier:', multiplier)
print()

# Task 4: Multiply columns
result4 = # Your code here
print('Task 4 (column-wise multiply):\n', result4)
print()

# Task 5: Add to each row
adder = np.array([100, 200, 300])
result5 = # Your code here
print('Task 5 (add to each row):\n', result5)

print('\n' + '='*60)
print('PART C: REAL-WORLD APPLICATIONS')
print('='*60 + '\n')

# Task 6: Normalize grades
grades = np.array([[85, 90, 78],
                   [92, 88, 76],
                   [79, 95, 82]])

print('Original Grades:\n', grades)
normalized = # Your code here (subtract mean, divide by std)
print('Normalized Grades:\n', normalized)
print('New Mean:', normalized.mean())
print('New Std:', normalized.std())
print()

# Task 7: Celsius to Fahrenheit
celsius = np.array([[0, 10, 20],
                    [30, 40, 50]])

print('Celsius:\n', celsius)
fahrenheit = # Your code here (C * 9/5 + 32)
print('Fahrenheit:\n', fahrenheit)


<details>
<summary>✅ <b>Click here for Solutions</b></summary>

```python
import numpy as np

# PART A: SCALAR BROADCASTING

# Task 1: 3×4 ones + 10
arr1 = np.ones((3, 4)) + 10
print('Task 1:\n', arr1)
# Output: All values = 11.0

# Task 2: Multiply by 5
arr2 = np.array([5, 10, 15, 20]) * 5
print('Task 2:', arr2)  # [25 50 75 100]

# Task 3: Random - 0.5
arr3 = np.random.random((2, 3)) - 0.5
print('Task 3:\n', arr3)
# Output: Random values shifted down by 0.5

# PART B: 1D to 2D BROADCASTING

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
multiplier = np.array([10, 20, 30])

# Task 4: Column-wise multiply
result4 = matrix * multiplier
print('Task 4:\n', result4)
# [[ 10  40  90]
#  [ 40 100 180]
#  [ 70 160 270]]
# Each column multiplied: col0*10, col1*20, col2*30

# Task 5: Add to each row
adder = np.array([100, 200, 300])
result5 = matrix + adder
print('Task 5:\n', result5)
# [[101 202 303]
#  [104 205 306]
#  [107 208 309]]
# Added [100,200,300] to each row

# PART C: REAL-WORLD APPLICATIONS

# Task 6: Normalize grades
grades = np.array([[85, 90, 78],
                   [92, 88, 76],
                   [79, 95, 82]])

mean = grades.mean()
std = grades.std()
normalized = (grades - mean) / std
print('Normalized:\n', normalized)
print('New Mean:', normalized.mean())  # ~0 (very close to 0)
print('New Std:', normalized.std())    # ~1.0
# This is z-score normalization used in ML!

# Task 7: Celsius to Fahrenheit
celsius = np.array([[0, 10, 20],
                    [30, 40, 50]])

fahrenheit = celsius * 9/5 + 32
print('Fahrenheit:\n', fahrenheit)
# [[ 32  50  68]
#  [ 86 104 122]]
```

**🎉 Amazing!** You've mastered broadcasting!

**Why Broadcasting is Powerful:**
1. **No explicit loops** - Code is clean and fast
2. **Memory efficient** - Smaller array isn't duplicated
3. **Vectorized** - Runs at C speed, not Python speed

**Broadcasting in Machine Learning:**
- **Normalization**: Scale features to same range (z-score)
- **Batch operations**: Apply operations to multiple samples at once
- **Neural networks**: Add bias to each neuron in a layer
- **Image processing**: Apply filters to all pixels

**The Magic:**
```python
# Without broadcasting (slow):
for i in range(rows):
    for j in range(cols):
        result[i][j] = arr[i][j] + 10

# With broadcasting (fast):
result = arr + 10  # Done!
```

</details>
---


*Matrix operations*

In [199]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [200]:
A

array([[1, 2],
       [3, 4]])

In [201]:
B

array([[5, 6],
       [7, 8]])

In [202]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [203]:
A

array([[1, 2],
       [3, 4]])

In [204]:
# transpose
A.T

array([[1, 3],
       [2, 4]])

In [205]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

c = A * B        # element-wise multiplication
d =np.dot(A,B)  # matrix multiplication
print(c)
print(d)

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


**Advance Array Manipulation**

*Stacking Array*

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [ ]:
np.vstack((a,b))

In [ ]:
np.hstack((a,b))

In [ ]:
np.column_stack((a,b))

*Splitting array*

In [ ]:
c = np.arange(16).reshape(4, 4)
c

In [ ]:
np.hsplit(c,2)

In [ ]:
np.vsplit(c,2)

**LOGICAL SELECTION**

In [ ]:
import numpy as np

arr = np.array([1,3, 4, 5])

# select elements greater than 2
result = arr[arr > 2]

print(result)

In [ ]:
print(arr[arr == 2])

In [ ]:
# Multiple conditions (AND)
print(arr[(arr > 1) & (arr % 2 == 0)])

In [ ]:
import numpy as np

arr = np.array([[1,2,4],
                [4,2,6]])

print(arr[arr > 3])

In [ ]:
print(arr[arr % 2 == 0])

In [ ]:
arr[arr > 3] = 0
print(arr)

**DELETING**

In [ ]:
arr = np.array([1,2,3,4])
new_arr = np.delete(arr, 1)
new_arr

In [ ]:
import numpy as np

arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

# delete row at index 1
new_arr = np.delete(arr, 1, axis=1)

print(new_arr)

In [ ]:
new_arr1 = np.append(arr, [2,3,4])
new_arr1

In [ ]:
new_arr2 = np.append(arr, [[1,2,3]], axis=0)
new_arr2

In [ ]:
np.insert(arr, 1, [7,8,9], axis=0)   # row
np.insert(arr, 1, [7,8,9], axis=1)     # column